apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook
  namespace: dev-vinh
webhooks:
  - name: validation.dev-vinh.svc
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1","v1beta1"]
    rules:
      - apiGroups: ["apps", ""]
        resources:
          - "pods"
        apiVersions:
          - "*"
        operations:
          - CREATE
          - UPDATE
          - DELETE
    clientConfig:
      service:
        name: validation
        namespace: dev-vinh
        path: /validate/
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQrekNDQXVPZ0F3SUJBZ0lVZTJ3WjVyT2VLMTV4WWZwbFozV2NPVWpUTldNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2V6RUxNQWtHQTFVRUJoTUNWVk14Q3pBSkJnTlZCQWdNQWxWVE1Rc3dDUVlEVlFRSERBSlZVekVMTUFrRwpBMVVFQ2d3Q1ZWTXhDekFKQmdOVkJBc01BbFZUTVNBd0hnWURWUVFEREJkMllXeHBaR0YwYVc5dUxtUmxkaTEyCmFXNW9Mbk4yWXpFV01CUUdDU3FHU0liM0RRRUpBUllIWVVCaExtTnZiVEFlRncweU5EQXpNRFV3TmpVeE1UZGEKRncweU5qRXlNalF3TmpVeE1UZGFNSHN4Q3pBSkJnTlZCQVlUQWxWVE1Rc3dDUVlEVlFRSURBSlZVekVMTUFrRwpBMVVFQnd3Q1ZWTXhDekFKQmdOVkJBb01BbFZUTVFzd0NRWURWUVFMREFKVlV6RWdNQjRHQTFVRUF3d1hkbUZzCmFXUmhkR2x2Ymk1a1pYWXRkbWx1YUM1emRtTXhGakFVQmdrcWhraUc5dzBCQ1FFV0IyRkFZUzVqYjIwd2dnRWkKTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDMDU4ekVlaHVKTnNPUXY1V2FPYmVXVWlBTwo0ZFhxYXdReVRUd0FnUlZSeXA4Yll2Z1ZaY1hKanovRUp5MWhRQXdadDNQQXFwUkZNejYyV1lhR250d3RxcHl2Ci9PNEl2eVVUZlVpczdYckduOVlMVHdIbTJTVzhmZWl3WmxNRGdhQlYzRnNMSUZoTVIrQzgrMitDYnAvRUZQQ1IKS2dzSkE0YUR1WjlxSlZGT2dMc2t2UkpNKytTSUFwbFhlSWlnM09TU1krVzJxKzB6YkFSOVFwbzdGb2dMellCNgo4RGZtVjlPRHRxQWdpWFZvRWpnNlgrdWxVRDZxRDdHeFhYUHdTekN1WElQTUhYUWVQMTNDUlZudUZ1Mnp4Y0hBCmxCV0J2K2RkMnZodXN0M0YzZXpab3l1dzkxem5naDMycEZxRlpEMTdtZ0d2Q2JVcTFSaW1wZ1hiY1RneEFnTUIKQUFHamR6QjFNQjBHQTFVZERnUVdCQlEwSGR3ZEtPclpwVFd6ZHYwMmJYSTR2aUhSS2pBZkJnTlZIU01FR0RBVwpnQlEwSGR3ZEtPclpwVFd6ZHYwMmJYSTR2aUhSS2pBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUNJR0ExVWRFUVFiCk1CbUNGM1poYkdsa1lYUnBiMjR1WkdWMkxYWnBibWd1YzNaak1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ2oKNlpjWWpvcWNwSERaOVRISzVhQUVabFhra0J6ZHFDTWxXbnhtbUU2Nkk4eXNML1Q1NlpvdHFBcWdIVG9HSW1zMgp5UDJEclJ3dEZSeTYzb1NMcTRhclNnbHkwbk9iSncvWFZGanNmMXRzbFFNRDFJbFBPeFZ4MjFmN1dyYzd4aFRYCnlzSHV4M3c2WHlZVEgrUUJWWDRmaThSQ2kxMXVkbUFMbVQ0ckhsYTRZWmZBRUMrWHdjdG9IUUlFdk8zSVJ5Y24KZ3l6NHhTNHM0MWZNbUhFbHI4aElUUmk2TUd2OCtwazRDcWtQdkhSdHJXejAwdERyOVBpMmVTNER6VFhRSkV3NApWaGMwa2pDeUUrdGMvbnFaZlJ5cStxMTBiR0drQmlqRnFXWkYrLy9XbTZEMVVqZjJyWWd5TVJoSmg4VmM2NnFECmJENWI0bzA0TXVNMGV4WUJsRjg0Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K

